version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:13.8
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      #POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - dados:/var/lib/postgresql/data 
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/create_tables.sql
      #- ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
    #- dados:/var/lib/postgresql/data
    #- ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql